// Growlane Consulting &mdash; site content
const CALENDLY = "https://calendly.com/ichoudharyudit/new-meeting";
const EMAIL = "udit@growlaneconsulting.com";
const INSTAGRAM = "https://www.instagram.com/growlane.consulting/";

const CONTENT = {
  brand: "Growlane Consulting",

  nav: [
    { label: "Home", href: "#/" },
    { label: "Services", href: "#/services" },
    { label: "Portfolio", href: "#/portfolio" },
    { label: "About", href: "#/about" },
    { label: "Blog", href: "#/blog" },
    { label: "Contact", href: "#/contact" },
  ],

  footerNav: [
    { label: "Home", href: "#/" },
    { label: "Services", href: "#/services" },
    { label: "Portfolio", href: "#/portfolio" },
    { label: "About", href: "#/about" },
    { label: "Healthcare Websites", href: "#/healthcare-websites" },
    { label: "Blog", href: "#/blog" },
    { label: "Contact", href: "#/contact" },
  ],

  heroPills: ["Medspa Websites", "Dermatology", "Dental Practices", "Weight Loss Clinics", "Wellness Practices"],

  problems: [
    { icon: "gauge", title: "Pages that load like it's 2014", body: "Your site takes six-plus seconds to load on mobile. Half your prospective patients are gone before they see anything." },
    { icon: "cursor", title: "No real online booking", body: "Just a phone number and a hope. Patients today expect to book in the same tap they used to find you." },
    { icon: "shield", title: "Compliance gaps nobody flagged", body: "Intake forms and booking pages built with no thought for HIPAA-conscious data handling, until something goes wrong." },
    { icon: "block", title: "One generic page for every provider", body: "No way for a patient to find or book a specific dermatologist, dentist, or provider by name." },
    { icon: "ghost", title: "Agencies that don't know healthcare", body: "A generalist agency treats your intake form like a contact form. It isn't one, and it shows." },
    { icon: "split", title: "One site, several locations, all outdated", body: "A multi-location practice or hospital group sharing one dated site that serves none of its locations well." },
  ],

  fixes: [
    { icon: "bolt", title: "Built for speed, by default", body: "Every site ships lean &mdash; optimized assets, minimal JavaScript, sub-two-second loads on mobile." },
    { icon: "target", title: "One-click booking flows", body: "Appointment requests that take under a minute, with clear confirmation and automated reminders." },
    { icon: "cross", title: "HIPAA-conscious from day one", body: "Secure forms, BAA-ready vendors when any field could capture PHI, and intake kept separate from marketing tools." },
    { icon: "user", title: "A page per provider", body: "So a patient can find, learn about, and book a specific provider, not just call a generic front desk." },
    { icon: "layers", title: "Accessible by default", body: "WCAG-conscious contrast, structure, and navigation, tested with screen readers before launch." },
    { icon: "doc", title: "One clean system, every location", body: "A single location-finder and consistent booking experience across every site in a multi-location group." },
  ],

  comparison: {
    headers: ["Growlane", "Typical Agency", "Freelancer"],
    rows: [
      ["Timeline", "2–4 weeks", "8–12+ weeks", "Unpredictable"],
      ["Single point of contact", "Yes, the whole way", "Relayed through an account manager", "Yes, but no backup if they're out"],
      ["Post-launch support", "30 days included", "Usually a separate retainer", "Rare, ask nicely"],
      ["Pricing", "Fixed, agreed upfront", "Scope creep is common", "Hourly, hard to predict"],
      ["Design + development, one team", "Yes", "Often outsourced separately", "Depends on the person"],
      ["Built with conversion in mind", "Yes, baked into the process", "Sometimes", "Rarely the focus"],
    ],
  },

  process: [
    { num: "01", title: "Audit", body: "We review your current site, your patients' actual booking path, and exactly what's stopping them from scheduling." },
    { num: "02", title: "Design & Build", body: "A custom visual direction and a hand-coded build, reviewed together in two structured rounds, with booking built in from page one." },
    { num: "03", title: "Launch & Support", body: "We deploy, test across every device, and stay on for 30 days after you go live to fix whatever real patients find first." },
  ],

  features: [
    { icon: "board", title: "One simple project board", body: "Track every request and revision in a shared Notion board &mdash; no inbox archaeology." },
    { icon: "tag", title: "One flat price, always", body: "No hourly surprises. You approve the scope once, and that's what you pay." },
    { icon: "bolt", title: "Fast turnaround", body: "Most practice sites ship in two to four weeks from kickoff to launch." },
    { icon: "star", title: "Senior work, every time", body: "No trainees learning on your project. You work directly with senior design and dev." },
    { icon: "lock", title: "100 percent yours", body: "Custom code, fully owned by you. No platform lock-in, no recurring license fees." },
    { icon: "toggle", title: "You stay in control", body: "Pause, adjust, or extend the engagement whenever your business needs it to change." },
  ],

  stats: [
    { value: "2&ndash;4 wks", label: "Typical time to launch" },
    { value: "1 team", label: "Strategy through launch, no handoffs" },
    { value: "30 days", label: "Post-launch support included" },
    { value: "100%", label: "Client-owned code, no lock-in" },
  ],

  industries: ["Medspas", "Dermatology", "Dental Practices", "IVF & Fertility", "Weight Loss Clinics", "Wellness Practices", "PT & Chiro", "Plastic Surgery"],

  testimonials: [
    { name: "Priya Shah", role: "Founder, Bloom Dental Studio", initials: "PS", quote: "Growlane rebuilt our booking flow and our site finally looks like the practice we actually run. New patient bookings are up since week one." },
    { name: "Marcus Webb", role: "Owner, Northline Aesthetics Medspa", initials: "MW", quote: "We had zero online booking before. I explained what I needed once, and two weeks later patients could book a consultation at midnight." },
    { name: "Dana Ruiz", role: "Practice Administrator, Carver & Finch Dermatology", initials: "DR", quote: "Every other agency wanted a discovery call just to send a proposal. Growlane sent a fixed quote in two days, and it actually understood provider pages." },
    { name: "Tom Okafor", role: "Medical Director, Okafor Plastic Surgery", initials: "TO", quote: "Our old site was a Squarespace template held together with plugins. This one actually converts consultations, and it's ours outright." },
    { name: "Alicia Meyer", role: "Practice Manager, Meyer Family Medicine", initials: "AM", quote: "They asked about HIPAA-conscious intake forms before we even brought it up. That told us everything." },
    { name: "Jordan Reyes", role: "Founder, Reyes Weight Loss & Wellness", initials: "JR", quote: "Our old site buried the one thing patients actually wanted to do: book a consult. This one leads with it, and bookings followed." },
  ],

  faqs: [
    { q: "How long does a typical project take?", a: "Most single-practice sites run two to four weeks from kickoff to launch, depending on the number of providers and revision rounds involved. Multi-location groups and hospital systems can run a bit longer &mdash; we'll give you a specific timeline before you sign anything." },
    { q: "What's actually included in the price?", a: "Strategy, sitemap, copywriting, custom design, development, mobile optimization, two rounds of revisions, and 30 days of post-launch support. The quote you get is the price you pay &mdash; no line items appear later." },
    { q: "Do you only work with healthcare practices?", a: "Yes. Clinics, medspas, and hospitals are the only clients we take on, which is why every build ships with accessible booking flows, secure intake forms, and copy reviewed with compliance-minded practices in mind by default, not as an add-on." },
    { q: "What happens if I need changes after launch?", a: "You get 30 days of support included at no extra cost. After that, you can book changes as needed or move to an ongoing care plan." },
    { q: "Do I own the website once it's finished?", a: "Completely. You get the code and all assets &mdash; no platform lock-in, no recurring license fees to us, and no dependency on keeping us on retainer." },
    { q: "What platform do you build on?", a: "We hand-code every site on a modern, fast-loading stack rather than a drag-and-drop builder. If you need a CMS for blog or content updates, we set that up as part of the build." },
  ],

  blog: [
    {
      slug: "small-business-websites-fail-to-convert",
      category: "Strategy",
      date: "2026-08-03",
      readTime: "6 min read",
      title: "Why Most Small Business Websites Fail to Convert",
      excerpt: "Traffic isn't the problem for most sites we audit &mdash; the path from landing page to booked call is. Here's where it usually breaks.",
      gradient: "teal",
      body: [
        { type: "p", text: "When a founder tells us their website \"isn't working,\" the instinct is almost always to blame traffic. More ads, more SEO, more content. But when we audit a site that gets visitors and no bookings, the traffic is rarely the issue &mdash; the path from arrival to action is." },
        { type: "h", text: "The three-second test" },
        { type: "p", text: "A visitor should know what you do, who it's for, and what to do next within three seconds of landing. If your homepage opens with a hero image and a vague tagline instead of a clear offer, you're spending your best attention on decoration." },
        { type: "p", text: "This doesn't mean the design has to be plain. It means every visual choice &mdash; including gradients, animation, and imagery &mdash; has to point toward the same next action." },
        { type: "h", text: "One call to action per page, not five" },
        { type: "p", text: "We regularly see homepages with a \"Book a call\" button, a newsletter signup, a \"Learn more\" link, and a contact form, all competing for the same click. Pick the one action that matters most on that page and make everything else secondary." },
        { type: "quote", text: "A website with five calls to action has zero calls to action." },
        { type: "p", text: "If you're rebuilding or refreshing a site, start by writing down the single next step you want a visitor to take on each page. Everything else on that page should exist to support that one decision." },
      ],
    },
    {
      slug: "hipaa-conscious-website-requirements",
      category: "Healthcare",
      date: "2026-07-18",
      readTime: "7 min read",
      title: "What a HIPAA-Conscious Website Actually Requires",
      excerpt: "Most practice websites treat compliance as an afterthought. Here's what to check before your next intake form goes live.",
      gradient: "indigo",
      body: [
        { type: "p", text: "\"HIPAA-compliant website\" isn't a certification you buy &mdash; HIPAA governs how protected health information is handled, not how a marketing page is styled. But most practice websites still create real exposure through forms, chat widgets, and hosting choices that were never evaluated." },
        { type: "h", text: "Where practice sites usually go wrong" },
        { type: "p", text: "The most common issue we find is a contact or intake form that emails patient details in plain text to a front-desk inbox, with no business associate agreement in place with the form vendor. The second most common is analytics or chat tools capturing identifiable health information without anyone realizing it." },
        { type: "h", text: "A practical checklist" },
        { type: "p", text: "Use a form provider willing to sign a BAA if any field could capture PHI. Route sensitive submissions to a secure system, not a shared inbox. Review any chat widget or analytics tool for what it logs. And keep your booking flow separate from any field that asks about symptoms or conditions." },
        { type: "p", text: "None of this requires a slower or less attractive website &mdash; it requires deciding on the data path before the form gets built, not after a complaint." },
      ],
    },
    {
      slug: "how-to-brief-a-website-project",
      category: "Workflow",
      date: "2026-06-27",
      readTime: "5 min read",
      title: "How to Brief a Website Project So It Doesn't Drag On",
      excerpt: "Most delays don't come from design or development — they come from a brief that never actually answered the questions a designer needs answered.",
      gradient: "violet",
      body: [
        { type: "p", text: "When a project runs long, it's rarely because the design took too many rounds or the code was hard to write. It's because the brief left too much open, and every open question turns into a round of back-and-forth that could have been settled on day one." },
        { type: "h", text: "The questions a brief actually needs to answer" },
        { type: "p", text: "Who is the single most important visitor to this site, and what should they do on it? What does this business actually sell, in one sentence a stranger would understand? What are the three things about this business that a generic template would never capture? A brief that answers these doesn't need to be long — it needs to be specific." },
        { type: "h", text: "Bring examples, not adjectives" },
        { type: "p", text: "\"Clean and modern\" describes almost every site on the internet and tells a designer nothing. Two or three sites you genuinely like, with a sentence on what you like about each, communicate more in five minutes than a mood board of adjectives ever will." },
        { type: "quote", text: "A good brief removes decisions, it doesn't just describe a vibe." },
        { type: "p", text: "The businesses that get through a build fastest aren't the ones with the fewest opinions — they're the ones who put those opinions in writing before the first design file opens, instead of discovering them one revision round at a time." },
      ],
    },
    {
      slug: "website-redesign-checklist",
      category: "Workflow",
      date: "2026-05-14",
      readTime: "8 min read",
      title: "Website Redesign Checklist: 12 Things to Get Right",
      excerpt: "Redesigning without a plan is how sites lose their SEO rankings overnight. Here's the checklist we run before touching anything live.",
      gradient: "teal",
      body: [
        { type: "p", text: "A redesign carries more risk than a first build, because you already have rankings, backlinks, and traffic patterns that a careless relaunch can wipe out overnight. Before we touch a single page, we run through the same checklist every time." },
        { type: "h", text: "Before you build" },
        { type: "p", text: "Audit current traffic and top-performing pages. Map every existing URL to its new destination. Export current analytics and search console data as a baseline. Confirm what content is actually working before deciding to cut it." },
        { type: "h", text: "During the build" },
        { type: "p", text: "Set up 301 redirects for every changed URL, not just the homepage. Keep heading structure and core keywords intact on pages that already rank. Test forms and booking flows on real devices, not just desktop Chrome." },
        { type: "h", text: "At launch" },
        { type: "p", text: "Resubmit your sitemap to search console. Watch indexing and traffic daily for the first two weeks. Keep the old hosting live for a short overlap window in case a rollback is needed." },
        { type: "p", text: "None of this is exciting work, but it's the difference between a redesign that grows your traffic and one that quietly resets it to zero." },
      ],
    },
    {
      slug: "seo-basics-for-local-business",
      category: "SEO",
      date: "2026-04-22",
      readTime: "6 min read",
      title: "SEO Basics Every Local Business Website Needs",
      excerpt: "Before you think about link building or content calendars, most local sites are missing five fundamentals. Start here.",
      gradient: "indigo",
      body: [
        { type: "p", text: "Local business owners often ask us about link building and content strategy before their site has the fundamentals in place. Fix these five things first &mdash; they matter more than anything else on the list." },
        { type: "h", text: "The five fundamentals" },
        { type: "p", text: "A claimed and complete Google Business Profile. A fast-loading, mobile-first site &mdash; Google measures this directly. One clear page per service you offer, not one page trying to cover everything. Consistent business name, address, and phone number everywhere you're listed. And basic technical hygiene: a sitemap, clean URLs, and working meta descriptions." },
        { type: "p", text: "Once those are solid, content and backlinks start to actually compound instead of propping up a broken foundation." },
      ],
    },
    {
      slug: "how-long-should-a-redesign-take",
      category: "Workflow",
      date: "2026-03-09",
      readTime: "4 min read",
      title: "How Long Should a Website Redesign Really Take?",
      excerpt: "If an agency quotes you six months for a marketing site, ask what's actually filling that time. Usually, not much.",
      gradient: "violet",
      body: [
        { type: "p", text: "A marketing website with under 15 pages should not take six months to redesign. If you're being quoted that timeline, ask specifically what's happening in months three and four &mdash; often the honest answer is queue time, not work." },
        { type: "h", text: "What a realistic timeline looks like" },
        { type: "p", text: "Discovery and strategy: three to five days. Design: one to two weeks, with two structured review rounds. Development: one to two weeks in parallel with final design polish. QA and launch: two to three days. That's two to four weeks for most small business sites, healthcare practices included." },
        { type: "p", text: "Longer timelines usually mean a bigger team relay, not more actual work &mdash; which is exactly the trade-off worth asking about before you sign." },
      ],
    },
  ],

  services: [
    { icon: "layout", title: "Medspa Websites", body: "A fully custom visual identity and page designs built around consultations and treatment bookings, not a generic salon template." },
    { icon: "cross", title: "Clinic & Practice Websites", body: "Dermatology, dental, and specialty clinic sites with a page per provider and booking built in from day one.", href: "#/healthcare-websites" },
    { icon: "code", title: "Hospital & Multi-Location Systems", body: "One consistent, fast-loading system across every location, with a single location-finder patients can actually use." },
    { icon: "target2", title: "Patient Booking Flows", body: "One-click appointment requests, provider-specific booking pages, and automated confirmations, live in days." },
    { icon: "refresh", title: "Practice Website Redesigns", body: "A careful rebuild that keeps your SEO equity intact while fixing what's actually holding new-patient bookings back." },
    { icon: "heart", title: "Ongoing Care Plans", body: "Monthly support for updates, new providers, and small fixes &mdash; so the site keeps working after we ship it." },
  ],

  healthcareProblems: [
    { icon: "shield", title: "Patient data handled like a newsletter signup", body: "A contact-form plugin with no business associate agreement, emailing intake details in plain text to a shared inbox." },
    { icon: "cursor", title: "Booking that assumes the patient isn't anxious", body: "Five fields and a dropdown before a patient ever sees a provider's face or an open time slot." },
    { icon: "block", title: "A design that reads corporate, not caring", body: "Stock photography and copy that could belong to any business, at exactly the moment a patient is deciding whether to trust you." },
  ],
  healthcareFixes: [
    { icon: "bolt", title: "A BAA-ready intake, by default", body: "Forms routed through vendors willing to sign a business associate agreement wherever a field could capture PHI." },
    { icon: "target", title: "The provider and the time slot, first", body: "Patients see who they'd see and when, before being asked for a single personal detail." },
    { icon: "layers", title: "Built to feel like your practice, not a template", body: "Real photography guidance and copy written for how your patients actually decide, not filler text with your logo on it." },
  ],

  caseStudies: [
    {
      tag: "Medspa",
      icon: "sparkle",
      gradient: "teal",
      image: "images/medspa-facial.png",
      title: "A medspa with zero online booking",
      before: "Consultations were booked entirely by phone, and the phone often went to voicemail after 5pm.",
      after: "A booking flow live in one click from the homepage, open around the clock, with automated confirmations.",
      impact: "Patients now book a consultation in under a minute, any time of day, without ever picking up the phone.",
      note: "Illustrative example.",
    },
    {
      tag: "Dermatology & Dental",
      icon: "tooth",
      gradient: "indigo",
      image: "images/dental-treatment-room.png",
      title: "One page trying to represent six providers",
      before: "Every dermatologist and dentist listed on a single page, with no way to request a specific provider.",
      after: "A dedicated booking page per provider, with intake handled online before the patient's first visit.",
      impact: "No more provider mix-ups at the front desk. Patients pick the right specialist and show up already checked in.",
      note: "Illustrative example.",
    },
    {
      tag: "Multi-Location Hospital Group",
      icon: "building",
      gradient: "violet",
      image: "images/dental-waiting-room.png",
      title: "Five locations, one dated shared site",
      before: "A hospital group's five locations sharing one outdated site with no reliable way to find the nearest one.",
      after: "One clean location-finder and consistent, HIPAA-conscious booking across every location.",
      impact: "Every location now shows accurate hours, directions, and a booking form patients actually trust.",
      note: "Illustrative example.",
    },
    {
      tag: "IVF & Fertility",
      icon: "heart",
      gradient: "rose",
      title: "A fertility clinic explaining treatment in medical jargon",
      before: "Treatment pages written for other doctors, not for anxious patients trying to understand their options.",
      after: "Plain-language treatment pages and a discreet, judgment-free way to request a first consultation online.",
      impact: "Patients say they finally understood their options before ever picking up the phone.",
      note: "Illustrative example.",
    },
    {
      tag: "Weight Loss Clinic",
      icon: "target",
      gradient: "amber",
      title: "A weight loss clinic that looked like a diet fad site",
      before: "Stock photography and before-and-after claims that made the practice look like a supplement ad, not a medical clinic.",
      after: "A clinical, credible design that leads with the medical team and a straightforward consultation booking.",
      impact: "Inquiries now come from patients who already trust it's a real medical program, not a gimmick.",
      note: "Illustrative example.",
    },
    {
      tag: "Wellness & PT/Chiro",
      icon: "layers",
      gradient: "sage",
      title: "A multi-provider wellness practice with one crowded homepage",
      before: "Chiropractic, physical therapy, and massage crammed onto a single page with no way to book a specific service.",
      after: "A clear service menu with its own booking flow per service, so patients book the right session the first time.",
      impact: "The front desk now fields far fewer “wait, do you do that here?” calls.",
      note: "Illustrative example.",
    },
    {
      tag: "Plastic Surgery",
      icon: "sparkle",
      gradient: "plum",
      title: "A plastic surgery practice with a portfolio nobody could browse",
      before: "Before-and-after photos buried in a PDF download, if they existed on the site at all.",
      after: "An organized, discreet results gallery patients can browse by procedure before booking a consultation.",
      impact: "Consultation requests now reference specific procedures and results by name.",
      note: "Illustrative example.",
    },
    {
      tag: "Solo Dental Practice · Warm & Boutique",
      icon: "tooth",
      gradient: "terracotta",
      title: "A single-dentist practice that read like a franchise",
      before: "A templated site with stock imagery that could have belonged to any dental office in the country.",
      after: "A warm, personal homepage built around the actual dentist and practice, with one clear booking CTA.",
      impact: "Patients now mention how welcoming the practice felt online, before they've even walked in.",
      note: "Style reference",
      refLink: "https://dentalo.framer.website/",
    },
    {
      tag: "Cosmetic Dentistry · Bold & Dramatic",
      icon: "sparkle",
      gradient: "noir",
      title: "A cosmetic practice with no way to show its own results",
      before: "A plain list of services and prices, with nothing to show what the actual work looks like.",
      after: "A dark, high-contrast before-and-after gallery patients browse before ever requesting a consultation.",
      impact: "Consultation requests now reference specific cases from the gallery by name.",
      note: "Style reference",
      refLink: "https://optident.framer.website/",
    },
    {
      tag: "Family Practice · Bright & Award-Led",
      icon: "badge",
      gradient: "citrus",
      title: "A well-regarded practice whose site undersold it",
      before: "Years of awards and five-star reviews, buried under a dated site that mentioned none of it.",
      after: "A confident, bright homepage that leads with credentials and trust markers, not just a service list.",
      impact: "New patients now arrive already sold, instead of needing to be convinced at the front desk.",
      note: "Style reference",
      refLink: "https://dentava.framer.website/",
    },
    {
      tag: "General Dentistry · Trust-Badge Led",
      icon: "star",
      gradient: "azure",
      title: "22,000 five-star reviews, invisible on the homepage",
      before: "A strong review history and years of experience that never showed up until page four of a Google search.",
      after: "Star rating and years-of-experience surfaced right in the hero, before a patient ever has to scroll.",
      impact: "Patients arrive already reassured, doing the trust-building the old site never did.",
      note: "Style reference",
      refLink: "https://oracarenew.framer.website/",
    },
  ],

  aboutValues: [
    { icon: "target", title: "Strategy first", body: "We don't open a design file until we know what the site needs to accomplish and for whom." },
    { icon: "user", title: "One owner, start to finish", body: "You work with the same person from kickoff to launch &mdash; no relay race between departments." },
    { icon: "doc", title: "Straight answers", body: "Fixed pricing, real timelines, and no scope surprises three weeks into the project." },
    { icon: "heart", title: "Built to be kept", body: "You own the code. If we ever stop working together, your site keeps working." },
  ],
};
